# Generated by Django 4.1.4 on 2022-12-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('payment', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('expiry_m', models.CharField(max_length=2, verbose_name='Срок (Месяц)')),
                ('expiry_y', models.CharField(max_length=4, verbose_name='Срок (Год)')),
                ('cvc', models.CharField(max_length=3, verbose_name='CVC код')),
            ],
        ),
    ]
