# Generated by Django 4.1.4 on 2022-12-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_persons_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='payment',
        ),
    ]
