# Generated by Django 4.1.4 on 2022-12-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_persons_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='Номер карты'),
        ),
    ]
